### ISSUE TITLE
More permissive license

### ISSUE THREAD

**Issue by mckaydavis** [noisyboiler/wampy#31]
The GPL3 license attached to wampy requires that any code that utilizes this library for WAMP transport to also be released under GPL3.

For example, this would mean any and all server microservices code I create using wampy must also be released as be open-source -- which I do not wish to do.

I strongly believe this choice of the GPL3 license will greatly hinder community adoption and code contribution back to this project.

I suggest changing it to a much more permissive MIT/BSD style license.

edit: pertinent discussion here: http://davidherron.com/blog/2014-04-26/whats-best-open-source-license-nodejs-modules

**Comment by noisyboiler** [comment]
Hi @mckaydavis 
understood. i'll look into it asap.
thanks

**Comment by noisyboiler** [comment]
Hi again @mckaydavis 
progress https://github.com/noisyboiler/wampy/wiki/License
but still no decision!
however, i will be moving away from GPL3, that's for sure - so thanks.
What's you opinion on the Lesser GPL license?
Thanks

**Comment by noisyboiler** [comment]
sorted
