### ISSUE TITLE
Travis Builds are Broken

### ISSUE THREAD

**Issue by noisyboiler** [noisyboiler/wampy#41]
This is a pain.

wampy uses eventlet under the hood for non-blocking IO. Travis recently move to 2.7.13 from 2.7.10. There is a bug that requires eventlet < 0.21.0 after making this move.
The issue is here: https://github.com/eventlet/eventlet/issues/401

But wampy requires eventlet >= 0.21.0 to avoid an SSL recursion bug in 3.6
The issue is here: https://github.com/eventlet/eventlet/issues/371

Options that I see are:
- abandon Python 2 entirely
- abandon Travis
- wait for one of the bugs to be fixed
- accept broken builds
- ask for hellp

I am now asking for help.....

Thanks

**Comment by titilambert** [comment]
@noisyboiler Maybe "abandon Travis":  did you thing about using circle CI ? 
https://circleci.com/docs/2.0/language-python/

Do you want I try to port tests with circle CI ? crossbar.io could be run in a docker container. which could clean the output of all tests...

**Comment by titilambert** [comment]
@noisyboiler Hello ! I think I got something here !
