### ISSUE TITLE
Example: Ticket authentication

### ISSUE THREAD

**Issue by wodCZ** [noisyboiler/wampy#66]
Hello,
for beginning, thank you for this package.

I've just implemented wampy to our stack, and I have some code that I think would be useful for readme or examples.
In our stack, Crossbar router runs in separate docker container, and is configured to use ticket authentication (which is not natively supported in wampy).

First, I created a new `TicketAuthenticate` class - message that will be sent after `ticket` challenge.
It receives `ticket` in constructor.
```py
class TicketAuthenticate(object):
    WAMP_CODE = 5
    name = "authenticate"

    def __init__(self, ticket, kwargs_dict=None):
        super(TicketAuthenticate, self).__init__()

        self.ticket = ticket
        self.kwargs_dict = kwargs_dict or {}

    @property
    def message(self):
        return [
            self.WAMP_CODE, self.ticket, self.kwargs_dict
        ]
```

Then, I extended `MessageHandler` to respond with this message in `handle_challenge`. It receives ticket in constructor and passes it to `TicketAuthenticate` once requested.

```py
from wampy.message_handler import MessageHandler, logger

class TicketMessageHandler(MessageHandler):

    ticket = None

    def __init__(self, ticket) -> None:
        super().__init__()
        self.ticket = ticket

    def handle_challenge(self, message_obj):
        logger.debug("client has been Challenged")
        message = TicketAuthenticate(self.ticket)
        self.session.send_message(message)
```

And finally usage example
```py
        roles = {
            'roles': {
                'subscriber': {},
                'publisher': {},
                'callee': {
                    'shared_registration': True,
                },
                'caller': {},
            },
            'authmethods': ['ticket'],
            'authid': settings.WAMP_BACKEND_PRINCIPAL
        }
        self.client = Client(
            url=f"ws://{settings.WAMP_BACKEND_HOST}:{settings.WAMP_BACKEND_PORT}",
            realm=settings.WAMP_BACKEND_REALM,
            roles=roles,
            message_handler=TicketMessageHandler(settings.WAMP_BACKEND_TICKET)
        )
        self.client.start()
```

I'm not a Python developer, but I feel that this code is not the best approach - that's why I'm creating this issue - it's not suitable for a pull request. 
It could save some time to anyone though, maybe it would be an inspiration for adding a support for ticket auth to wampy.

Please let me know whether you want this issue to be closed without discussion (just kept for reference), or you'd like to discuss this topic.

Thanks!

**Comment by noisyboiler** [comment]
Hi @wodCZ 
Many thanks for your interest and your use-case here. I'm really pleased that someone has harnessed this extension point in wampy! this is exactly what it is there for.
I'll take a good read over the next few days and get back to you.
Thanks again

**Comment by dmugtasimov** [comment]
Hi @noisyboiler . Thank you for the package. Is there any advance on the implementing ticket authentication in wampy natively? Because I need it, too.

**Comment by noisyboiler** [comment]
hiya.
thanks for getting in touch. I have some time in the coming weeks actually and could get this in then,  but you or @wodCZ are very welcome to raise a PR in the meantime?

**Comment by dmugtasimov** [comment]
@noisyboiler sorry, I do not file like I have time to prepare a PR in a near future.
