### ISSUE TITLE
flask example

### ISSUE THREAD

**Issue by keiser1080** [noisyboiler/wampy#69]
Hi,

On the description i see wampy can be used in a webapp.
I have read the doc, and there are multiple example for standalone application,
but no example of using wampy inside a web application.
Could you post or add on the docs or on the example folder a simple flask example ?
I have a flask aplication exposing an http service, 
and i want to extend it by publishing toward a crossbar router some event.

**Comment by noisyboiler** [comment]
Hi @keiser1080 
good point! I've actually only used **wampy** with **nameko**, so I'll try out Flask asap and get an integration guide together asap.
Thank you for raising this.

**Comment by keiser1080** [comment]
Hi,

Hi don't think it feasable.
Because to combine with flask your application must be statefull.

Actually it's stateless, fo r example you can not use a sessions.




Le 10 nov. 2018 16:20, "simon" <notifications@github.com> a écrit :

this is still on my radar.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/noisyboiler/wampy/issues/69#issuecomment-437591179>,
or mute
the thread

**Comment by noisyboiler** [comment]
much like nameko integration needs a bespoke project, Flask will too. The very beginning: https://github.com/noisyboiler/flask-wamp

**Comment by keiser1080** [comment]
Great!

**Comment by noisyboiler** [comment]
here you go! https://github.com/noisyboiler/flask-wamp

**Comment by noisyboiler** [comment]
https://pypi.org/project/Flask-WAMP/
