### ISSUE TITLE
Python 3.7 Support

### ISSUE THREAD

**Issue by edstafford** [noisyboiler/wampy#94]
Biggest issue at the moment is usage of the reserved word async. Will update with further findings.

**Comment by noisyboiler** [comment]
thanks, @edstafford 

I think it's a Crossbar issue though? It's not on their build job: https://travis-ci.org/crossbario/crossbar, and although *wampy* is not tested on 3.7, it does not use that keyword.

Whilst neither project is yet able to officially support 3.7 can you not create an env using 3.6 for now, to achieve what you need?

**Comment by noisyboiler** [comment]
wanna add 3.7 to the **wampy**Travis build so we can see the results?

**Comment by edstafford** [comment]
You are correct, I didn't read the stack trace correctly.

**Comment by edstafford** [comment]
I think if we could remove the direct dependency on crossbar that we could move the library forward faster.

**Comment by noisyboiler** [comment]
that's a good idea 👍

**Comment by noisyboiler** [comment]
@edstafford tests pass on 3.7 and 3.7.3 now.
it's only taken a year and a half!

**Comment by edstafford** [comment]
I'm glad I could help! :(
